# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageProcess_dialog_base.ui'
#
# Created: Sat Jun 08 01:36:13 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageProcessDialogBase(object):
    def setupUi(self, ImageProcessDialogBase):
        ImageProcessDialogBase.setObjectName(_fromUtf8("ImageProcessDialogBase"))
        ImageProcessDialogBase.resize(881, 567)
        ImageProcessDialogBase.setFocusPolicy(QtCore.Qt.StrongFocus)
        ImageProcessDialogBase.setSizeGripEnabled(False)
        self.verticalLayoutWidget = QtGui.QWidget(ImageProcessDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 321))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 140, 251, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gBox_kmeans = QtGui.QGroupBox(self.groupBox)
        self.gBox_kmeans.setGeometry(QtCore.QRect(10, 60, 251, 81))
        self.gBox_kmeans.setCheckable(True)
        self.gBox_kmeans.setObjectName(_fromUtf8("gBox_kmeans"))
        self.label = QtGui.QLabel(self.gBox_kmeans)
        self.label.setGeometry(QtCore.QRect(60, 10, 141, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.sBox_cNum = QtGui.QSpinBox(self.gBox_kmeans)
        self.sBox_cNum.setGeometry(QtCore.QRect(30, 51, 81, 21))
        self.sBox_cNum.setMinimum(2)
        self.sBox_cNum.setMaximum(10)
        self.sBox_cNum.setProperty("value", 2)
        self.sBox_cNum.setObjectName(_fromUtf8("sBox_cNum"))
        self.btn_kmeans = QtGui.QPushButton(self.gBox_kmeans)
        self.btn_kmeans.setGeometry(QtCore.QRect(140, 50, 75, 23))
        self.btn_kmeans.setObjectName(_fromUtf8("btn_kmeans"))
        self.gBox_isodata = QtGui.QGroupBox(self.groupBox)
        self.gBox_isodata.setGeometry(QtCore.QRect(10, 160, 251, 151))
        self.gBox_isodata.setCheckable(True)
        self.gBox_isodata.setChecked(True)
        self.gBox_isodata.setObjectName(_fromUtf8("gBox_isodata"))
        self.label_4 = QtGui.QLabel(self.gBox_isodata)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.gBox_isodata)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 16, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.gBox_isodata)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.gBox_isodata)
        self.label_7.setGeometry(QtCore.QRect(130, 20, 21, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.gBox_isodata)
        self.label_8.setGeometry(QtCore.QRect(130, 50, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.gBox_isodata)
        self.label_9.setGeometry(QtCore.QRect(130, 80, 21, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.K = QtGui.QLineEdit(self.gBox_isodata)
        self.K.setGeometry(QtCore.QRect(40, 20, 61, 20))
        self.K.setObjectName(_fromUtf8("K"))
        self.L = QtGui.QLineEdit(self.gBox_isodata)
        self.L.setGeometry(QtCore.QRect(40, 50, 61, 20))
        self.L.setObjectName(_fromUtf8("L"))
        self.I = QtGui.QLineEdit(self.gBox_isodata)
        self.I.setGeometry(QtCore.QRect(40, 80, 61, 20))
        self.I.setObjectName(_fromUtf8("I"))
        self.TN = QtGui.QLineEdit(self.gBox_isodata)
        self.TN.setGeometry(QtCore.QRect(160, 20, 61, 20))
        self.TN.setObjectName(_fromUtf8("TN"))
        self.TS = QtGui.QLineEdit(self.gBox_isodata)
        self.TS.setGeometry(QtCore.QRect(160, 50, 61, 21))
        self.TS.setObjectName(_fromUtf8("TS"))
        self.TC = QtGui.QLineEdit(self.gBox_isodata)
        self.TC.setGeometry(QtCore.QRect(160, 80, 61, 21))
        self.TC.setObjectName(_fromUtf8("TC"))
        self.btn_isodata = QtGui.QPushButton(self.gBox_isodata)
        self.btn_isodata.setGeometry(QtCore.QRect(80, 110, 91, 31))
        self.btn_isodata.setObjectName(_fromUtf8("btn_isodata"))
        self.btn_LoadImages = QtGui.QPushButton(self.groupBox)
        self.btn_LoadImages.setGeometry(QtCore.QRect(80, 20, 91, 31))
        self.btn_LoadImages.setObjectName(_fromUtf8("btn_LoadImages"))
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtGui.QWidget(ImageProcessDialogBase)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 10, 321, 551))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.img_display = QtGui.QLabel(self.groupBox_5)
        self.img_display.setGeometry(QtCore.QRect(10, 20, 301, 521))
        self.img_display.setText(_fromUtf8(""))
        self.img_display.setObjectName(_fromUtf8("img_display"))
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.verticalLayoutWidget_3 = QtGui.QWidget(ImageProcessDialogBase)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 340, 281, 221))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.verticalLayoutWidget_3)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.tabWidget = QtGui.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 261, 191))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.P_1 = QtGui.QLineEdit(self.tab)
        self.P_1.setGeometry(QtCore.QRect(80, 70, 91, 21))
        self.P_1.setObjectName(_fromUtf8("P_1"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.P_2 = QtGui.QLineEdit(self.tab)
        self.P_2.setGeometry(QtCore.QRect(80, 100, 91, 20))
        self.P_2.setObjectName(_fromUtf8("P_2"))
        self.comboBox_TM3 = QtGui.QComboBox(self.tab)
        self.comboBox_TM3.setGeometry(QtCore.QRect(80, 10, 161, 22))
        self.comboBox_TM3.setObjectName(_fromUtf8("comboBox_TM3"))
        self.comboBox_TM4 = QtGui.QComboBox(self.tab)
        self.comboBox_TM4.setGeometry(QtCore.QRect(80, 40, 161, 22))
        self.comboBox_TM4.setObjectName(_fromUtf8("comboBox_TM4"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(30, 10, 16, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(30, 40, 21, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.P_NDVI = QtGui.QPushButton(self.tab)
        self.P_NDVI.setGeometry(QtCore.QRect(180, 70, 61, 23))
        self.P_NDVI.setObjectName(_fromUtf8("P_NDVI"))
        self.P_RVI = QtGui.QPushButton(self.tab)
        self.P_RVI.setGeometry(QtCore.QRect(180, 100, 61, 23))
        self.P_RVI.setObjectName(_fromUtf8("P_RVI"))
        self.P_progress = QtGui.QProgressBar(self.tab)
        self.P_progress.setGeometry(QtCore.QRect(10, 130, 231, 23))
        self.P_progress.setMaximum(301602)
        self.P_progress.setProperty("value", 0)
        self.P_progress.setObjectName(_fromUtf8("P_progress"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 21, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(30, 40, 21, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBox_TM3_2 = QtGui.QComboBox(self.tab_2)
        self.comboBox_TM3_2.setGeometry(QtCore.QRect(80, 10, 161, 22))
        self.comboBox_TM3_2.setObjectName(_fromUtf8("comboBox_TM3_2"))
        self.W_1 = QtGui.QLineEdit(self.tab_2)
        self.W_1.setGeometry(QtCore.QRect(80, 70, 91, 21))
        self.W_1.setObjectName(_fromUtf8("W_1"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.W_2 = QtGui.QLineEdit(self.tab_2)
        self.W_2.setGeometry(QtCore.QRect(80, 100, 91, 20))
        self.W_2.setObjectName(_fromUtf8("W_2"))
        self.W_progress = QtGui.QProgressBar(self.tab_2)
        self.W_progress.setGeometry(QtCore.QRect(10, 130, 231, 23))
        self.W_progress.setMaximum(301602)
        self.W_progress.setProperty("value", 0)
        self.W_progress.setObjectName(_fromUtf8("W_progress"))
        self.comboBox_TM4_2 = QtGui.QComboBox(self.tab_2)
        self.comboBox_TM4_2.setGeometry(QtCore.QRect(80, 40, 161, 22))
        self.comboBox_TM4_2.setObjectName(_fromUtf8("comboBox_TM4_2"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 61, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.W_NDVI = QtGui.QPushButton(self.tab_2)
        self.W_NDVI.setGeometry(QtCore.QRect(180, 70, 61, 23))
        self.W_NDVI.setObjectName(_fromUtf8("W_NDVI"))
        self.W_R = QtGui.QPushButton(self.tab_2)
        self.W_R.setGeometry(QtCore.QRect(180, 100, 61, 23))
        self.W_R.setObjectName(_fromUtf8("W_R"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.comboBox_TM4_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_TM4_3.setGeometry(QtCore.QRect(80, 40, 161, 22))
        self.comboBox_TM4_3.setObjectName(_fromUtf8("comboBox_TM4_3"))
        self.comboBox_TM3_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_TM3_3.setGeometry(QtCore.QRect(80, 10, 161, 22))
        self.comboBox_TM3_3.setObjectName(_fromUtf8("comboBox_TM3_3"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(30, 10, 16, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(30, 40, 21, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.btn_cloud = QtGui.QPushButton(self.tab_4)
        self.btn_cloud.setGeometry(QtCore.QRect(84, 80, 81, 31))
        self.btn_cloud.setObjectName(_fromUtf8("btn_cloud"))
        self.C_progress = QtGui.QProgressBar(self.tab_4)
        self.C_progress.setGeometry(QtCore.QRect(10, 130, 231, 23))
        self.C_progress.setMaximum(301602)
        self.C_progress.setProperty("value", 0)
        self.C_progress.setObjectName(_fromUtf8("C_progress"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayoutWidget_4 = QtGui.QWidget(ImageProcessDialogBase)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(630, 10, 241, 141))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.verticalLayoutWidget_4)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 50, 201, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.btn_remove = QtGui.QPushButton(self.groupBox_3)
        self.btn_remove.setGeometry(QtCore.QRect(80, 10, 81, 31))
        self.btn_remove.setObjectName(_fromUtf8("btn_remove"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.LogText)
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayoutWidget_5 = QtGui.QWidget(ImageProcessDialogBase)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(630, 160, 241, 191))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.verticalLayoutWidget_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.hist_display = QtGui.QLabel(self.groupBox_6)
        self.hist_display.setGeometry(QtCore.QRect(10, 20, 221, 161))
        self.hist_display.setText(_fromUtf8(""))
        self.hist_display.setObjectName(_fromUtf8("hist_display"))
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.verticalLayoutWidget_6 = QtGui.QWidget(ImageProcessDialogBase)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(630, 360, 241, 201))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.verticalLayoutWidget_6)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.btn_Merge = QtGui.QPushButton(self.groupBox_4)
        self.btn_Merge.setGeometry(QtCore.QRect(80, 110, 81, 31))
        self.btn_Merge.setObjectName(_fromUtf8("btn_Merge"))
        self.comboBox_rgb = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_rgb.setGeometry(QtCore.QRect(60, 60, 161, 22))
        self.comboBox_rgb.setObjectName(_fromUtf8("comboBox_rgb"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 41, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.comboBox_gray = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_gray.setGeometry(QtCore.QRect(60, 30, 161, 22))
        self.comboBox_gray.setObjectName(_fromUtf8("comboBox_gray"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.M_progress = QtGui.QProgressBar(self.groupBox_4)
        self.M_progress.setGeometry(QtCore.QRect(10, 160, 221, 23))
        self.M_progress.setMaximum(301602)
        self.M_progress.setProperty("value", 0)
        self.M_progress.setObjectName(_fromUtf8("M_progress"))
        self.verticalLayout_6.addWidget(self.groupBox_4)

        self.retranslateUi(ImageProcessDialogBase)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ImageProcessDialogBase)

    def retranslateUi(self, ImageProcessDialogBase):
        ImageProcessDialogBase.setWindowTitle(_translate("ImageProcessDialogBase", "Image Process", None))
        self.groupBox.setTitle(_translate("ImageProcessDialogBase", "Unsupervised Classification", None))
        self.gBox_kmeans.setTitle(_translate("ImageProcessDialogBase", "K-Means", None))
        self.label.setText(_translate("ImageProcessDialogBase", "Num of classifications", None))
        self.btn_kmeans.setText(_translate("ImageProcessDialogBase", "Execute", None))
        self.gBox_isodata.setTitle(_translate("ImageProcessDialogBase", "ISODATA", None))
        self.label_4.setText(_translate("ImageProcessDialogBase", "K", None))
        self.label_5.setText(_translate("ImageProcessDialogBase", "L", None))
        self.label_6.setText(_translate("ImageProcessDialogBase", "I", None))
        self.label_7.setText(_translate("ImageProcessDialogBase", "TN", None))
        self.label_8.setText(_translate("ImageProcessDialogBase", "TS", None))
        self.label_9.setText(_translate("ImageProcessDialogBase", "TC", None))
        self.btn_isodata.setText(_translate("ImageProcessDialogBase", "Execute", None))
        self.btn_LoadImages.setText(_translate("ImageProcessDialogBase", "Load Images", None))
        self.groupBox_5.setTitle(_translate("ImageProcessDialogBase", "Image Display", None))
        self.groupBox_2.setTitle(_translate("ImageProcessDialogBase", "Feature Extraction", None))
        self.label_3.setText(_translate("ImageProcessDialogBase", "Threshold1", None))
        self.label_10.setText(_translate("ImageProcessDialogBase", "Threshold2", None))
        self.label_11.setText(_translate("ImageProcessDialogBase", "R", None))
        self.label_12.setText(_translate("ImageProcessDialogBase", "NIR", None))
        self.P_NDVI.setText(_translate("ImageProcessDialogBase", "NDVI", None))
        self.P_RVI.setText(_translate("ImageProcessDialogBase", "RVI", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImageProcessDialogBase", "Plant", None))
        self.label_13.setText(_translate("ImageProcessDialogBase", "R", None))
        self.label_14.setText(_translate("ImageProcessDialogBase", "NIR", None))
        self.label_15.setText(_translate("ImageProcessDialogBase", "Threshold2", None))
        self.label_16.setText(_translate("ImageProcessDialogBase", "Threshold1", None))
        self.W_NDVI.setText(_translate("ImageProcessDialogBase", "NDVI", None))
        self.W_R.setText(_translate("ImageProcessDialogBase", "IR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ImageProcessDialogBase", "Water", None))
        self.label_17.setText(_translate("ImageProcessDialogBase", "R", None))
        self.label_18.setText(_translate("ImageProcessDialogBase", "NIR", None))
        self.btn_cloud.setText(_translate("ImageProcessDialogBase", "Execute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ImageProcessDialogBase", "Cloud", None))
        self.groupBox_3.setTitle(_translate("ImageProcessDialogBase", "Layers", None))
        self.btn_remove.setText(_translate("ImageProcessDialogBase", "Remove", None))
        self.label_2.setText(_translate("ImageProcessDialogBase", "All images in the list are included\n"
"in clustering by deflult\n"
"Remove the ones you don\'t want", None))
        self.groupBox_6.setTitle(_translate("ImageProcessDialogBase", "Hist", None))
        self.groupBox_4.setTitle(_translate("ImageProcessDialogBase", "Merge Images", None))
        self.btn_Merge.setText(_translate("ImageProcessDialogBase", "Merge", None))
        self.label_19.setText(_translate("ImageProcessDialogBase", "Gray", None))
        self.label_20.setText(_translate("ImageProcessDialogBase", "Color", None))

